FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

# set the working directory
#WORKDIR /usr/src/project
WORKDIR /app

# install dependencies
# COPY ./requirements.txt ./
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Set PYTHONPATH to include the application directory
# ENV PYTHONPATH=/usr/src/project/application
# ENV PYTHONPATH=/app/src

# copy application code
# COPY ./application ./application
COPY . .

#EXPOSE 8080
ENV PORT=8080
EXPOSE 8080

# FASTAPI / STREAMLIT
#ENTRYPOINT ["streamlit", "run", "application/streamlit_page.py", "--server.port=8080", "--server.address=0.0.0.0"]

# start the server
#CMD ["uvicorn", "main_chatwoot:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers"]
CMD ["sh", "-c", "uvicorn main_chatwoot_ia_off:app --host 0.0.0.0 --port ${PORT}"]