FROM python:3.12-slim

ENV PYTHONUNBUFFERED True

# set the working directory
#WORKDIR /usr/src/project
WORKDIR /app

# install dependencies
# COPY ./requirements.txt ./
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Set PYTHONPATH to include the application directory
# ENV PYTHONPATH=/usr/src/project/application
ENV PYTHONPATH=/app/src

# copy application code
COPY ./application ./application

#EXPOSE 8080
ENV PORT=4000
EXPOSE 4000

# FASTAPI / STREAMLIT
#ENTRYPOINT ["streamlit", "run", "application/streamlit_page.py", "--server.port=4000", "--server.address=0.0.0.0"]

# start the server
#CMD ["uvicorn", "main_chatwoot:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers"]
CMD ["sh", "-c", "uvicorn main_chatwoot-ia_off.main:app --host 0.0.0.0 --port ${PORT}"]