name: Deploy to Cloud Run

env:
  SERVICE_NAME: servicio-backend-agente-inmobiliaria-seg-lulebebe
  PROJECT_ID: inmobiliaria-lulebebe
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/inmobiliaria-lulebebe/repositorio-inmobiliaria-seguridad/imagen-backend-inmobiliaria-seg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SECRETO_GOOGLE_INMOBILIARIA }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile.prod .
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying $SERVICE_NAME"
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --service-account=seg-observabilidad-inmobiliari@inmobiliaria-lulebebe.iam.gserviceaccount.com \
            --update-secrets="AGENT_TIMEZONE=AGENT_TIMEZONE:1,CHATWOOT_ACCOUNT_ID=CHATWOOT_ACCOUNT_ID:1,CHATWOOT_API_ACCESS_TOKEN=CHATWOOT_API_ACCESS_TOKEN:1,CHATWOOT_BASE_URL=CHATWOOT_BASE_URL:1,DB_HOST=DB_HOST:1,DB_NAME=DB_NAME:1,DB_PASSWORD=DB_PASSWORD:1,DB_PORT=DB_PORT:1,DB_USER=DB_USER:1,OPENAI_API_KEY=OPENAI_API_KEY:1,QDRANT_API_KEY=QDRANT_API_KEY:1,QDRANT_COLLECTION=QDRANT_COLLECTION:1,QDRANT_URL=QDRANT_URL:1,TAVILY_API_KEY=TAVILY_API_KEY:1,GROQ_API_KEY=GROQ_API_KEY:1,LANGFUSE_SECRET_KEY=LANGFUSE_SECRET_KEY:1,LANGFUSE_PUBLIC_KEY=LANGFUSE_PUBLIC_KEY:1,LANGFUSE_BASE_URL=LANGFUSE_BASE_URL:1,REDIS_HOST=REDIS_HOST:1,REDIS_PORT=REDIS_PORT:1,REDIS_DB=REDIS_DB:1,REDIS_PASSWORD=REDIS_PASSWORD:1 " \
            --update-secrets="/secrets/google/service-account.json=GOOGLE_APPLICATION_CREDENTIALS:1" \
            --set-env-vars="GOOGLE_APPLICATION_CREDENTIALEG=/secrets/google/service-account.json"